### ISSUE TITLE
Newer versions of roundcube seem to use config.inc.php (instead of main.inc.php)

### ISSUE THREAD

**Issue by cbj4074** [w2c/ispconfig3_roundcube#52]
It's been a while since I had to follow the installation instructions, but it seems that in some fairly recent version of `roundcube`, the configuration file name was changed from `main.inc.php` to `config.inc.php`.

There appears to be some ambiguity because the roundcube installation instructions at http://trac.roundcube.net/wiki/Howto_Install still reference `main.inc.php` (under the `Other tutorials` section), but the `Configuring Roundcube` section does indeed refer to the newer file, `config.inc.php`.

I mention this primarily because I had copied my old `main.inc.php` from another roundcube installation to this new one, and the `Account` tab, which is normally added under `Settings` when this plugin is installed correctly, was absent.

It wasn't until I moved the plugin string array items from the `$rcmail_config['plugins']` array in `main.inc.php` to the `$config['plugins']` array in `config.inc.php` that the `Account` tab began to show-up.

I'm happy to submit a pull-request if the author is able to confirm that my assessment is accurate.

Thanks!

**Comment by cbj4074** [comment]
@Churro Care to offer any explanation as to why this was closed? Has the documentation been updated accordingly?

**Comment by Churro** [comment]
The reason this was closed is that it is no issue with our plugins rather than a general Roundcube thing.

The configuration file switch from main.inc.php to config.inc.php happened with Roundcube 1.0 (released on 5 Apr 2014), the release text highlighted the change very explicitly and (meanwhile?) it was also well described in the [official documentation](https://github.com/roundcube/roundcubemail/wiki/Configuration).

Now as there is nothing to fix or change from our side, I do not see any evident need to keep this open...

**Comment by cbj4074** [comment]
@Churro Thank you for explaining. That is perfectly reasonable. 👍
