### ISSUE TITLE
ISPConfig 3.1RC1: Soap Error: autoresponder_end_date_isgreater

### ISSUE THREAD

**Issue by ugoviti** [w2c/ispconfig3_roundcube#57]
Hi,

trying to set the autoresponder with ISPConfig 3.1 rc1 I get:

**Soap Error: autoresponder_end_date_isgreater**

And Apache log that into error_log:

```
[Mon Aug 15 14:30:20.997660 2016] [fcgid:warn] [pid 117524] [client ::1:37698] mod_fcgid: stderr: PHP Warning:  date_parse_from_format() expects parameter 2 to be string, array given in /usr/local/ispconfig/interface/lib/classes/tform_base.inc.php on line 1175
[Mon Aug 15 14:30:20.997682 2016] [fcgid:warn] [pid 117524] [client ::1:37698] mod_fcgid: stderr: PHP Warning:  date_parse_from_format() expects parameter 2 to be string, array given in /usr/local/ispconfig/interface/lib/classes/tform_base.inc.php on line 826
[Mon Aug 15 14:30:20.997688 2016] [fcgid:warn] [pid 117524] [client ::1:37698] mod_fcgid: stderr: PHP Warning:  date_parse_from_format() expects parameter 2 to be string, array given in /usr/local/ispconfig/interface/lib/classes/tform_base.inc.php on line 1175
[Mon Aug 15 14:30:20.997694 2016] [fcgid:warn] [pid 117524] [client ::1:37698] mod_fcgid: stderr: PHP Warning:  date_parse_from_format() expects parameter 2 to be string, array given in /usr/local/ispconfig/interface/lib/classes/validate_autoresponder.inc.php on line 55
[Mon Aug 15 14:30:20.997699 2016] [fcgid:warn] [pid 117524] [client ::1:37698] mod_fcgid: stderr: PHP Warning:  date_parse_from_format() expects parameter 2 to be string, array given in /usr/local/ispconfig/interface/lib/classes/validate_autoresponder.inc.php on line 56
[Mon Aug 15 14:30:20.997705 2016] [fcgid:warn] [pid 117524] [client ::1:37698] mod_fcgid: stderr: PHP Warning:  date_parse_from_format() expects parameter 2 to be string, array given in /usr/local/ispconfig/interface/lib/classes/tform_base.inc.php on line 826
```

With kind regards

**Comment by vladki77** [comment]
This error appear whenever I try to set anything using the roundcube/ispconfig plugin - not only autoresponder, but also password or forwarding address. Moreover, autoresponder plugin does not show anything, unles an autoreply is already set up. But even then it does not work and the above error is shown when any changes are submitted.

**Comment by QuocurIQ** [comment]
Same issue here. Checked time zones as some posts suggested, Also tried setting the dates to null. Still the same.

**Comment by itsburkina** [comment]
Same issue here
https://git.ispconfig.org/ispconfig/ispconfig3/issues/3823

**Comment by andreasspeck** [comment]
Exactly the same issue.
Changing default values to NULL in ispconfig3_autoreply.php does not do anything either.

The same error also appears when trying to use any of the other plugins.

**Comment by Churro** [comment]
With commit 9a7e64cc0ce2efb0919f9cdd70a7a59be9302442, we now added compatibility with Ispconfig 3.1 **final**. Important: This is not work with 3.1 RC1 - except if you adapt something in the code --> see below for more info.

**What was the problem?**
Ispconfig did some major changes that broke compatibility with this addon. Unlike suspected, it had nothing to do with the default date code that was changed from 000-00-00 00:00:00 to NULL. Instead, they introduced a [new date validation routine](https://git.ispconfig.org/ispconfig/ispconfig3/commit/96ae77f9f14f3e1381fa3e5405c693b0273ce1d2) expecting the date as a string that is then parsed. So starting with any version of 3.1, the way we provided the date was fine.

**Why does our patch not work natively with 3.1 RC1?**
Basically, the reason is that 3.1 RC1 still has some bugs (which is actually not that surprising for an RC version). 

_First issue_: In order to maintain compatibility with older versions of Ispconfig, our Roundcube addon now knows the old and new way to speak with Ispconfig. However, in order to know which way to go, we have to find out which version of Ispconfig we are running. However, the  API method to find it out, is not included in 3.1 RC1. It will be there in 3.1 final or any 3.1 RC2 but not it is actually **not** in 3.1 RC1. 
_Second issue_: In 3.1 RC1, the way the provided date string is decomposed by Ispconfig depends on the language setting of the user. So we would have to send an individual date format for every possible setting.

Both problems have been addressed by Ispconfig. Patches are in the stable-3.1 branch, so it can be assumed that they will also be in any upcoming version of 3.1.

**How to make this Roundcube addon work with Ispconfig 3.1 RC1?**
As described above, Ispconfig 3.1 RC1 is missing a SOAP method and lacks a user-independent date formatter. The solution is, hence, to add a few lines to Ispconfig yourself.

Two possible ways:

1. Modify _/usr/local/ispconfig/interface/lib/classes/remote.d/server.inc.php_ and add the _server_get_app_version method_ at the end of the file from [here](https://git.ispconfig.org/ispconfig/ispconfig3/commit/4a258fa5e11b0c392a7faebbca8914f8c9a86b4c). Modify _/usr/local/ispconfig/interface/lib/classes/remoting_lib.inc.php_ and change the values for dateformat and datetimeformat with the ones noted [here](https://git.ispconfig.org/ispconfig/ispconfig3/commit/d0fc52e1b37025f6fc42833bd607568655405364).

2. Simply replace the entire _interface/lib/classes/remote.d/server.inc.php_ file with a [patched](https://git.ispconfig.org/ispconfig/ispconfig3/blob/stable-3.1/interface/lib/classes/remote.d/server.inc.php) one. Likewise, exchange the file _interface/lib/classes/remoting_lib.inc.php_, with a [bugfixed](https://git.ispconfig.org/ispconfig/ispconfig3/blob/stable-3.1/interface/lib/classes/remoting_lib.inc.php) one. 

So, long story short: Our plugin should work out-of-the-box with any upcoming release of Ispconfig 3.1 and, of course, also any older. Due to bugs in Ispconfig 3.1 RC1, however, the described modifications are necessary.

**Comment by zoltanlaczko** [comment]
What about 3.1dev (git-stable) ?

**Comment by vladki77** [comment]
I have tried updating the roundcube plugin and patched the above mentioned files, but still get the same error.

**Comment by zoltanlaczko** [comment]
I tried with 3.1dev (git-stable) with the latest plugin and still have the issue.

**Comment by Churro** [comment]
Well, 3.1dev is not 3.1rc1 ;-)

The check we introduced with commit https://github.com/w2c/ispconfig3_roundcube/commit/9a7e64cc0ce2efb0919f9cdd70a7a59be9302442 targeted 3.1rc1 or any newer version. Since the current stable-3.1 branch of ISPconfig identifies as 3.1dev, it was not matched since a development version usually precedes a release candidate.

Commit https://github.com/w2c/ispconfig3_roundcube/commit/900b15e1872a12e8d1b64d3cdd6f55d51313f509 now lowers this barrier to 3.1dev.

**Comment by vladki77** [comment]
Thanks now the autoreply, junk policy and forwarding works fine. 
However the password change does not work. It warns if something is wrong (too short, no numbers in password, wrong old password), but if it is ok, a blank page returns and the password is not changed. No error in error.log.

**Comment by Churro** [comment]
Thanks for the hint! This was a copy/paste error on our side... has been fixed with commit https://github.com/w2c/ispconfig3_roundcube/commit/7aae7736500f7fd2bfb188ec8f3cd5533f2b0a5c

**Comment by ugoviti** [comment]
Hi Churro,

thank you  very much for the patches... Tested right now with 3.1RC1 and works perfectly.

With kind regards

**Comment by vladki77** [comment]
Tested here as well and it is ok now. Well done Churro. Thank you

**Comment by zoltanlaczko** [comment]
After 900b15e it works with 3.1dev (git-stable) as well. Thanks!

**Comment by kosli** [comment]
Updated to the latest commit and works like a charm with the newly released ISPconfig 3.1.1

**Comment by giovannifour** [comment]
I updated just now to the latest commit and does not work with ispconfig version 3.1.1 (last stable ispconfig version)

**Comment by giovannifour** [comment]
Sorry. Now works :).

**Comment by aellert** [comment]
Hi there,

I have the same error message :

> Soap Error: autoresponder_end_date_isgreater

When the begin date is December 2016 and end date is in 2017.

Happy new year :)

**Comment by k0st4k** [comment]
I've updated to 3.1.2, i've checked both files, both are patched but i still have this issue:
What else should I do ?

[Mon Feb 20 12:49:00.587086 2017] [fcgid:warn] [pid 10387] [client 127.0.0.1:55412] mod_fcgid: stderr: PHP Warning:  date_parse_from_format() expects parameter 2 to be string, array given in /usr/local/ispconfig/interface/lib/classes/tform_base.inc.php on line 1185
[Mon Feb 20 12:49:00.587107 2017] [fcgid:warn] [pid 10387] [client 127.0.0.1:55412] mod_fcgid: stderr: PHP Warning:  date_parse_from_format() expects parameter 2 to be string, array given in /usr/local/ispconfig/interface/lib/classes/tform_base.inc.php on line 826
[Mon Feb 20 12:49:00.587109 2017] [fcgid:warn] [pid 10387] [client 127.0.0.1:55412] mod_fcgid: stderr: PHP Warning:  date_parse_from_format() expects parameter 2 to be string, array given in /usr/local/ispconfig/interface/lib/classes/tform_base.inc.php on line 1185
[Mon Feb 20 12:49:00.587112 2017] [fcgid:warn] [pid 10387] [client 127.0.0.1:55412] mod_fcgid: stderr: PHP Warning:  date_parse_from_format() expects parameter 2 to be string, array given in /usr/local/ispconfig/interface/lib/classes/validate_autoresponder.inc.php on line 55
[Mon Feb 20 12:49:00.587114 2017] [fcgid:warn] [pid 10387] [client 127.0.0.1:55412] mod_fcgid: stderr: PHP Warning:  date_parse_from_format() expects parameter 2 to be string, array given in /usr/local/ispconfig/interface/lib/classes/validate_autoresponder.inc.php on line 56
[Mon Feb 20 12:49:00.587123 2017] [fcgid:warn] [pid 10387] [client 127.0.0.1:55412] mod_fcgid: stderr: PHP Warning:  date_parse_from_format() expects parameter 2 to be string, array given in /usr/local/ispconfig/interface/lib/classes/tform_base.inc.php on line 826

**Comment by jcherqui** [comment]
:+1:

**Comment by Pesulap** [comment]
👍

**Comment by hubiktomas** [comment]
Hi, I am also having this issue. Roundcube Webmail 1.1.5 and ISPConfig 3.1.2.

**Comment by k0st4k** [comment]
Update plugins, it will help

Email z wt. mar 7 18:36:21 2017 GMT+0100 od hubiktomas:

**Comment by hubiktomas** [comment]
Oh, sorry. It works perfectly after update. :)

**Comment by keithkklee** [comment]
just update the roundcube plugin again, still have the same issue.
ISPConfig: 3.1.2

**Comment by wzurborg** [comment]
Still the same error here with ISPC 3.1.6.

**Comment by ketoraire** [comment]
Hi there,

We have the trouble too on our ISPConfig Instance.
I found a workaround.

The /usr/local/ispconfig/interface/lib/classes/validate_autoresponder.inc.php use the variable $app->lng('conf_format_datetime') to define the proper date format for the validation. 


The value of this variable is in /usr/local/ispconfig/interface/lib/lang

- In english the value is **Y-m-d H:i:s** and the API work great
- But in French, Canadian, Italian, Spanish, Malais the value is **d-m-Y H:i**

So after replacing d-m-Y H:i per Y-m-d H:i:s in my canadien/french file ... the API work fine again :)

**Comment by grobmotoriker** [comment]
> Hi there,
> 
> We have the trouble too on our ISPConfig Instance.
> I found a workaround.
> 
> The /usr/local/ispconfig/interface/lib/classes/validate_autoresponder.inc.php use the variable $app->lng('conf_format_datetime') to define the proper date format for the validation.
> 
> The value of this variable is in /usr/local/ispconfig/interface/lib/lang
> 
> * In english the value is **Y-m-d H:i:s** and the API work great
> * But in French, Canadian, Italian, Spanish, Malais the value is **d-m-Y H:i**
> 
> So after replacing d-m-Y H:i per Y-m-d H:i:s in my canadien/french file ... the API work fine again :)

That also did the trick for us - we're using ISPConfig 3.1.11 and updated the ISPConfig 3-Roundcube plugins, but it didn't work until we adapted the date format in the German language file.

**Comment by kosli** [comment]
@Churro  can you take a look at that issue plz? 
Merry Xmas!

**Comment by Churro** [comment]
Closing this issue as the original problem has already been fixed in 09/2016. The current autoreply bug seems related but is actually a different problem.
