### ISSUE TITLE
Autoreply

### ISSUE THREAD

**Issue by kosli** [w2c/ispconfig3_roundcube#85]
It seems not to be possible to choose a start date in November 2018. It gets set in ISPconfig correctly, but the plugin displays always the same day, just in December 2018 ?! No idea where to start looking at. Fyi, I am using the latest version from SVN.

**Comment by Accudio** [comment]
I can confirm I have the same issue.

Interestingly this is simply what is displayed, the input still contains the November date when you inspect the element, indicating a javascript issue. Given there is little javascript in the autoreply plugin, this might be related to the jQueryUI plugin as that is a standard datepicker widget.

The input is loaded with the correct time from ISPConfig, but there is a flash of it changing to the same date and time in December when scripts have run. It does this for every date I have tried in November, regardless of year, and no other month.

My debugging skills are not extensive however I can try take a look.

**Comment by Churro** [comment]
Hmm, I tried to reproduce the issue using FF 63, Chrome 70 and IE 11 but whatever start date I tried with in November 2018, the datetimepicker selected it the way you would expect. 
![2018-11-01 15_45_33-window](https://user-images.githubusercontent.com/343448/47860037-e6913b80-ddef-11e8-8dd7-429cf8f31f52.png)

When the page gets loaded, the corresponding HTML code should look like this (Firefox Dev Tools):
![2018-11-01 15_54_17-window](https://user-images.githubusercontent.com/343448/47860323-936bb880-ddf0-11e8-9407-d21e4e695bc6.png)

If the date format in the HTML looks the same in your case, it has to be an issue with the JavaScript datetimepicker. Most likely something goes wrong while parsing the date string. However, as there have been no changes to the datetimepicker script in a very long time, Nov'18 would either be an unhandled corner case or the fault is actually caused somewhere else.

**Comment by Churro** [comment]
Hi,

I think I can now reproduce the issue:
1. The Roundcube plugin always sends a date string in the format "Y-m-d H:i" to ISPConfig.
2. The API call `mail_user_update` internally calls the method `end_date()` from `/usr/local/ispconfig/interface/lib/classes/validate_autoresponder.inc.php`.
3. In this method, the date strings for the start and the end date are passed to the PHP-internal function `date_parse_from_format`, alongside with a format string, specified in `$app->lng('conf_format_datetime')`. In case an error happens while parsing the given date string, the function nonetheless fills the resulting array fields with implausible values, e.g. `["month"] => 18`. These fields are later used with `mktime()` to derive a UNIX timestamps for the start and end date. `mktime()` also doesn't complain about implausible values but generates a timestamp anyway. This is the reason, why this issue has a different origin than the one initially described in #57 and is only visible with certain dates.
4. In this case, the problem is the variable `$app->lng('conf_format_datetime')`. The used date format depends on the value `$conf['language']` is set to in `/usr/local/ispconfig/interface/lib/config.inc.php`. 

If `$conf['language']` specifies a language where `$wb['conf_format_datetime']` doesn't equal to ''Y-m-d H:i", the autoresponder date parsing will be spurious. This is the case, e.g. with the languages _de, ca, nl, fr, pt_.  

Thus, the workaround described in https://github.com/w2c/ispconfig3_roundcube/issues/57#issuecomment-445241861 is effective as it simply transforms the date format to the single one that is supported. Another workaround would be to set `$conf['language']` to _en_. The advantage of the latter one is that it will also survive updates of ISPConfig, rather than changes in language files.

Besides these workarounds, there are two possible solutions:

- We can somehow obtain the value of `$conf['language']` in the plugin and hand over the date to ISPConfig in the correct format. This is currently unfeasible since ISPConfig provides no API call for retrieving this language setting.

- _Probably better approach:_ ISPConfig should eliminate the use of `$app->lng('conf_format_datetime')` from `validate_autoresponder.inc.php`. Actually, the ISPConfig API already [specifies a fixed date format](https://git.ispconfig.org/ispconfig/ispconfig3/blob/master/interface/lib/classes/remoting_lib.inc.php#L101), to which we comply. If `validate_autoresponder.php` would also use that setting, we would be fine and in addition, we wouldn't have to replicate all possible date format strings for each language.

Summarizing, I don't see how our plugin could find out what language is specified in ISPConfig's `config.inc.php`. As long as ISPConfig doesn't change this on their side, the only option you have are the two workarounds described above.

**Comment by kosli** [comment]
Thank you very much @Churro 
It seems this has been fixed in ISPconfig dev branch 3 weeks ago: https://git.ispconfig.org/ispconfig/ispconfig3/commit/1543ba74b27cc7aa63993ad9fd8c49915ea9b9ec
So I assume in the next release of ISPconfig we won't have that problem anymore. Great. Thanks!
